name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create Release
      id: create_release
      run: |
        gh release create ${{ github.ref_name }} \
          --title "Xbox Controller API ${{ github.ref_name }}" \
          --notes "## Xbox Controller Desktop Bridge ${{ github.ref_name }}
          
          A cross-platform desktop application that allows you to control your computer using an Xbox controller.
          
          ### Features
          - 🎮 Full Xbox controller support
          - 🖱️ Mouse control with analog sticks
          - ⌨️ Keyboard shortcuts and text input
          - 🎵 Media playback control
          - 🎙️ Voice input activation
          - ⚙️ Customizable button mappings
          
          ### Downloads
          - **Windows x64**: \`xbox-controller-api-windows-x64.zip\`
          - **Windows x86**: \`xbox-controller-api-windows-x86.zip\`
          - **Linux x64**: \`xbox-controller-api-linux-x64.tar.gz\`
          - **macOS x64**: \`xbox-controller-api-macos-x64.tar.gz\`
          - **macOS ARM64**: \`xbox-controller-api-macos-arm64.tar.gz\`
          
          ### Installation
          1. Download the appropriate package for your platform
          2. Extract the archive
          3. Run the executable
          
          ### Requirements
          - Windows: Windows 10 or later
          - Linux: X11 display server
          - macOS: macOS 10.15 or later
          
          ### Changelog
          - Initial release with core functionality
          - Cross-platform support
          - Configurable button mappings"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    needs: create-release
    uses: ./.github/workflows/windows.yml
    with:
      is_release: true
      tag_name: ${{ github.ref_name }}
    secrets: inherit

  build-linux:
    needs: create-release
    uses: ./.github/workflows/linux.yml
    with:
      is_release: true
      tag_name: ${{ github.ref_name }}
    secrets: inherit

  build-macos:
    needs: create-release
    uses: ./.github/workflows/macos.yml
    with:
      is_release: true
      tag_name: ${{ github.ref_name }}
    secrets: inherit