name: Windows Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  build-windows:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [x64, x86]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Install MinGW and dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          mingw-w64 \
          cmake \
          ninja-build \
          wget \
          unzip
          
    - name: Setup MinGW toolchain
      run: |
        if [ "${{ matrix.arch }}" = "x64" ]; then
          echo "CC=x86_64-w64-mingw32-gcc" >> $GITHUB_ENV
          echo "CXX=x86_64-w64-mingw32-g++" >> $GITHUB_ENV
          echo "CMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/cmake/mingw-w64-x86_64.cmake" >> $GITHUB_ENV
        else
          echo "CC=i686-w64-mingw32-gcc" >> $GITHUB_ENV
          echo "CXX=i686-w64-mingw32-g++" >> $GITHUB_ENV
          echo "CMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/cmake/mingw-w64-i686.cmake" >> $GITHUB_ENV
        fi
        
    - name: Create toolchain files
      run: |
        mkdir -p cmake
        
        # x64 toolchain
        cat > cmake/mingw-w64-x86_64.cmake << 'EOF'
        set(CMAKE_SYSTEM_NAME Windows)
        set(CMAKE_SYSTEM_PROCESSOR x86_64)
        
        set(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)
        set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)
        set(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres)
        
        set(CMAKE_FIND_ROOT_PATH /usr/x86_64-w64-mingw32)
        set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
        set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
        set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
        EOF
        
        # x86 toolchain
        cat > cmake/mingw-w64-i686.cmake << 'EOF'
        set(CMAKE_SYSTEM_NAME Windows)
        set(CMAKE_SYSTEM_PROCESSOR i686)
        
        set(CMAKE_C_COMPILER i686-w64-mingw32-gcc)
        set(CMAKE_CXX_COMPILER i686-w64-mingw32-g++)
        set(CMAKE_RC_COMPILER i686-w64-mingw32-windres)
        
        set(CMAKE_FIND_ROOT_PATH /usr/i686-w64-mingw32)
        set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
        set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
        set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
        EOF
        
    - name: Build SDL3 for Windows
      run: |
        wget https://github.com/libsdl-org/SDL/archive/refs/tags/release-3.2.16.tar.gz
        tar -xzf release-3.2.16.tar.gz
        cd SDL-release-3.2.16
        mkdir build && cd build
        cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=${{ env.CMAKE_TOOLCHAIN_FILE }} \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/SDL3-install \
          -DSDL_SHARED=ON \
          -DSDL_STATIC=OFF \
          -GNinja
        ninja
        ninja install
        
    - name: Configure CMake
      run: |
        cmake -B build -S . \
          -DCMAKE_TOOLCHAIN_FILE=${{ env.CMAKE_TOOLCHAIN_FILE }} \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_PREFIX_PATH=${{ github.workspace }}/SDL3-install \
          -GNinja
          
    - name: Build
      run: ninja -C build
      
    - name: Test
      run: |
        echo "Cross-compiled binaries cannot be tested on Linux host"
      
    - name: Package
      run: |
        mkdir -p package/xbox-controller-api
        
        # Copy main executable
        cp build/*.exe package/xbox-controller-api/ || true
        
        # Copy SDL3 DLLs
        cp ${{ github.workspace }}/SDL3-install/bin/*.dll package/xbox-controller-api/ || true
        
        # Copy MinGW runtime DLLs
        if [ "${{ matrix.arch }}" = "x64" ]; then
          cp /usr/x86_64-w64-mingw32/lib/libwinpthread-1.dll package/xbox-controller-api/ || true
          cp /usr/lib/gcc/x86_64-w64-mingw32/*/libgcc_s_seh-1.dll package/xbox-controller-api/ || true
          cp /usr/lib/gcc/x86_64-w64-mingw32/*/libstdc++-6.dll package/xbox-controller-api/ || true
        else
          cp /usr/i686-w64-mingw32/lib/libwinpthread-1.dll package/xbox-controller-api/ || true
          cp /usr/lib/gcc/i686-w64-mingw32/*/libgcc_s_dw2-1.dll package/xbox-controller-api/ || true
          cp /usr/lib/gcc/i686-w64-mingw32/*/libstdc++-6.dll package/xbox-controller-api/ || true
        fi
        
        # List all files for debugging
        echo "Package contents:"
        ls -la package/xbox-controller-api/
        
        # Create zip
        cd package
        zip -r ../xbox-controller-api-windows-${{ matrix.arch }}.zip xbox-controller-api
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: xbox-controller-api-windows-${{ matrix.arch }}
        path: xbox-controller-api-windows-${{ matrix.arch }}.zip
        
    - name: Upload to release
      if: github.event_name == 'workflow_call' && startsWith(github.ref, 'refs/tags/')
      run: |
        gh release upload ${{ github.ref_name }} xbox-controller-api-windows-${{ matrix.arch }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}